Fix timezone aware issues
Because every dates should be timezone "aware" :)

This PR fix errors of timezone when the pypykatz project is compiled from an **pipenv** environment and the lsa minidump command throws this error:
```
  File "/root/.local/share/virtualenvs/minidump-pJ0wrUgQ/lib/python3.7/site-packages/asn1crypto-1.2.0-py3.7.egg/asn1crypto/core.py", line 5083, in set
    raise ValueError('Must be timezone aware')
ValueError: Must be timezone aware
    while constructing minikerberos.asn1_structs.KerberosTime
    while constructing minikerberos.asn1_structs.KrbCredInfo
```